apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume2
        configMap:
          name: nginx-html2
          items:
          - key: index.html
            path: index.html
